query headwayTimeSeries($params: HeadwayInputType!) {
  headwayMetrics {
    headwayTimeSeries(inputs: $params) {
      ts
      actual: actualWaitTime
      scheduled: scheduledWaitTime
      excess: excessWaitTime
    }
  }
}

query headwayOverview($params: HeadwayInputType!) {
  headwayMetrics {
    headwayOverview(inputs: $params) {
      excess: excessWaitTime
    }
  }
}

query headwayFrequentServices(
  $operatorId: String!
  $fromTimestamp: Date!
  $toTimestamp: Date!
) {
  headwayMetrics {
    frequentServices(
      operatorId: $operatorId
      fromTimestamp: $fromTimestamp
      toTimestamp: $toTimestamp
    ) {
      serviceId
    }
  }
}

query headwayFrequentServiceInfo($inputs: FrequentServiceInfoInputType!) {
  headwayMetrics {
    frequentServiceInfo(inputs: $inputs) {
      numHours
      totalHours
    }
  }
}
