import type { ColumnType } from "kysely";
export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Alert = {
  id: Generated<string>;
  alert_id: string | null;
  alert: string | null;
  event_hysterisis: string | null;
  event_threshold: string | null;
  send_to: number | null;
  created_by: number | null;
};
export type all_operators = {
  operatorid: number | null;
  operatorref: string;
  name: string | null;
};
export type ApiInfo = {
  id: string;
  version: string;
  build_number: string;
  timezone: string;
  feature_flag_id: string;
};
export type avl_line_level_monitoring = {
  operator_noc: string;
  line_name: string;
  last_recorded_at_time: Timestamp;
};
export type bods_organisation = {
  id: number;
  name: string | null;
  is_abods_global_viewer: boolean | null;
};
export type bods_organisationoperator = {
  organisation_id: number;
  operatorref: string;
};
export type bods_user = {
  id: number;
  username: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  password: string;
  is_superuser: boolean | null;
  is_active: boolean | null;
  account_type: number | null;
  admin_org: number | null;
};
export type bods_userorganisation = {
  user_id: number;
  organisation_id: number;
};
export type corridor = {
  corridor_id: Generated<number>;
  corridor_name: string;
  organisation_id: number;
  user_id: number;
};
export type corridor_stops = {
  corridor_index: number;
  corridor_id: number;
  stop_id: number;
};
export type distinct_routes = {
  id: Generated<number>;
  route: string;
};
export type expected_journeys = {
  date_of_journey: Timestamp;
  operator_noc: string | null;
  line_name: string | null;
  noc_and_line_and_servicecode: string;
  journey_code: string;
  group_id: string;
  stop_count: number | null;
  expected_journey_start: Timestamp | null;
  journey_pattern_description: string;
  vehicle_journey_id: number | null;
  day_of_week: number | null;
  admin_area_id: number[];
  expected_journey_end: Timestamp | null;
  direction: string | null;
};
export type expected_operators = {
  date_of_journey: Timestamp;
  operator_noc: string;
  operator_name: string | null;
};
export type expected_services = {
  line_name: string;
  noc_and_line_and_servicecode: string;
  service_name: string;
  date_of_journey: Timestamp;
  operator_noc: string;
  admin_area_id: number[];
};
export type FeatureFlag = {
  id: string;
  consolidate_histogram: boolean;
  corridor_stats_timezone_enabled: boolean;
  freshdesk_enabled: boolean;
  line_direction_filtering: boolean;
  sso_enabled: boolean;
  stop_index_filtering: boolean;
  tagging_include_bank_holidays: boolean;
  vehicle_replay_from_timestream: boolean;
  journey_insights_enabled: boolean;
};
export type feed_monitor_daily_summary = {
  id: Generated<string>;
  date_of_journey: Timestamp;
  operator_noc: string;
  update_frequency: number | null;
  availability: string | null;
};
export type feed_monitor_hourly_summary = {
  id: Generated<string>;
  operator_noc: string;
  received_interval: Timestamp;
  expected: number;
  actual: number;
};
export type feed_monitor_minute_summary = {
  id: Generated<string>;
  date_of_journey: Timestamp;
  operator_noc: string;
  received_interval: Timestamp;
  expected: number;
  actual: number;
  live_locations: number;
};
export type feed_monitor_summary = {
  id: Generated<string>;
  operator_noc: string;
  last_outage: Timestamp | null;
  unavailable_since: Timestamp | null;
  update_frequency: number | null;
  availability: string | null;
};
export type login_details = {
  user_id: number;
  last_login: Timestamp;
  data_monitoring_access_count: number | null;
  data_monitoring_access_refresh: Timestamp | null;
};
export type naptan_adminarea = {
  id: string;
  name: string;
  traveline_region_id: string;
  atco_code: string;
  ui_lta_id: number | null;
};
export type naptan_adminarea_with_shape = {
  id: number;
  name: string;
  atco_code: string | null;
  st_asgeojson: string;
};
export type naptan_locality = {
  gazetteer_id: string;
  name: string;
  easting: number;
  northing: number;
  admin_area_id: string;
  district_id: number | null;
};
export type naptan_stoppoint_latlong = {
  id: number;
  atco_code: string | null;
  naptan_code: string | null;
  common_name: string;
  street: string | null;
  indicator: string | null;
  admin_area_id: number;
  locality_id: string;
  stop_areas: string[];
  bus_stop_type: string | null;
  stop_type: string | null;
  longitude: number | null;
  latitude: number | null;
};
export type noc_adminarea = {
  national_operator_code: string;
  adminarea_id: number;
};
export type organisation_organisation_admin_areas = {
  id: number;
  organisation_id: number | null;
  adminarea_id: number | null;
};
export type performance_statistics = {
  operator_noc: string;
  line_name: string;
  noc_and_line_and_servicecode: string;
  service_name: string | null;
  is_timing_point: boolean | null;
  date_period_start: Timestamp;
  date_period_end: Timestamp | null;
  period_type: string;
  on_time_count: number | null;
  early_count: number | null;
  late_count: number | null;
  total_count: number | null;
  on_time_percentage: string | null;
  trend_period_start: Timestamp | null;
  trend_period_end: Timestamp | null;
  trend_on_time_count: number | null;
  trend_early_count: number | null;
  trend_late_count: number | null;
  trend_total_count: number | null;
  trend_percentage: string | null;
  percentage_change: string | null;
};
export type service_details = {
  noc_and_line_and_servicecode: string;
  operator_noc: string | null;
  line_name: string | null;
  service_name: string | null;
};
export type servicepattern_route = {
  distinct_route_id: number;
  noc_and_line_and_servicecode: string;
};
export type SiriVMPositions = {
  siri_vm_positions_id: Generated<string>;
  operator_ref: string;
  line_name: string;
  journey_ref: string;
  direction_ref: string | null;
  date_of_journey: Timestamp;
  latitude: number | null;
  longitude: number | null;
  vehicle_ref: string;
  batch_id: string | null;
  recorded_at_time: Timestamp;
  response_time_stamp: Timestamp | null;
  load_time_stamp: Generated<Timestamp | null>;
  group_id: string | null;
  origin_ref: string | null;
  destination_ref: string | null;
  departure_time: Timestamp | null;
};
export type Timetable = {
  timetable_id: Generated<string>;
  operator_noc: string;
  operator_name: string;
  service_code: string;
  line_name: string | null;
  xml_file_name: string | null;
  journey_code: string | null;
  date_of_journey: Timestamp;
  day_of_week: number | null;
  common_name: string | null;
  atco_code: string | null;
  stop_type: string | null;
  stop_index: number;
  stop_latitude: number | null;
  stop_longitude: number | null;
  locality_id: string | null;
  expected_departure_time: Timestamp | null;
  actual_departure_time: Timestamp | null;
  is_timing_point: boolean | null;
  group_id: string | null;
  previous_group_id: string | null;
  otp_state: string | null;
  expected_headway: number | null;
  actual_headway: number | null;
  headway_time_difference: number | null;
  time_difference: number | null;
  stop_id: number;
  load_time_stamp: Generated<Timestamp | null>;
  off_set: number | null;
  servicepattern_id: number | null;
  vehiclejourney_id: number | null;
  admin_area_id: number | null;
  timestamp_after_estimate: Timestamp | null;
  direction: string | null;
  departure_day_shift: boolean | null;
  siri_vm_position_id: string | null;
  incomplete_reason: number | null;
};
export type timetable_frequent_summary_services = {
  timetable_id: Generated<string>;
  operator_noc: string;
  service_code: string;
  noc_and_line_and_servicecode: string;
  line_name: string;
  date_of_journey: Timestamp;
  departure_hour: Timestamp;
  departure_hour_only: Timestamp;
  day_of_week: number;
  max_early: number;
  max_late: number;
  avg_time_difference: string;
  expected_headway: string;
  actual_headway: string;
  excess_wait_time: string;
  headway_stops_count: string;
  estimated: boolean;
  is_timing_point: boolean | null;
};
export type timetable_summary_operator_t = {
  timetable_id: Generated<string>;
  operator_noc: string;
  date_of_journey: Timestamp;
  departure_hour: Timestamp;
  departure_hour_only: Timestamp;
  day_of_week: number;
  on_time_count: number | null;
  early_count: number | null;
  late_count: number | null;
  completed: number | null;
  scheduled: number | null;
  is_timing_point: boolean;
  max_early: number;
  max_late: number;
  avg_time_difference: string;
  admin_areas: number[];
  estimated: Generated<boolean | null>;
  incomplete_reason: number | null;
};
export type timetable_summary_service_tz = {
  timetable_id: Generated<string>;
  operator_noc: string;
  line_name: string;
  noc_and_line_and_servicecode: string;
  date_of_journey: Timestamp;
  departure_hour: Timestamp;
  departure_hour_only: Timestamp;
  day_of_week: number;
  on_time_count: number | null;
  early_count: number | null;
  late_count: number | null;
  completed: number | null;
  scheduled: number | null;
  is_timing_point: boolean;
  max_early: number;
  max_late: number;
  avg_time_difference: string | null;
  admin_areas: number[];
  estimated: Generated<boolean>;
  incomplete_reason: number | null;
};
export type timetable_summary_stops_tz = {
  timetable_id: Generated<string>;
  operator_noc: string;
  service_code: string;
  noc_and_line_and_servicecode: string;
  stop_id: number;
  locality_id: string;
  line_name: string;
  stop_latitude: number;
  stop_longitude: number;
  date_of_journey: Timestamp;
  departure_hour: Timestamp;
  departure_hour_only: Timestamp;
  day_of_week: number;
  on_time_count: number | null;
  early_count: number | null;
  late_count: number | null;
  completed: number | null;
  scheduled: number | null;
  common_name: string;
  is_timing_point: boolean;
  max_early: number;
  max_late: number;
  avg_time_difference: string | null;
  estimated: Generated<boolean>;
  incomplete_reason: number | null;
};
export type timetable_threshold_summary = {
  threshold_id: Generated<string>;
  operator_noc: string | null;
  line_name: string | null;
  noc_and_line_and_servicecode: string | null;
  service_name: string | null;
  date_of_journey: Timestamp | null;
  is_timing_point: boolean | null;
  time_diff_minutes: number | null;
  departure_hour: Timestamp | null;
  admin_areas: number[];
  otp_count: number | null;
  day_of_week: number | null;
  estimated: Generated<boolean | null>;
  departure_hour_only: Timestamp | null;
};
export type Tokens = {
  user_id: number;
  token: string | null;
  expires: Generated<Timestamp | null>;
};
export type transmodel_servicepatternstop = {
  id: string;
  sequence_number: number;
  atco_code: string;
  naptan_stop_id: number;
  service_pattern_id: number;
  departure_time: Timestamp | null;
  is_timing_point: boolean;
  txc_common_name: string | null;
  vehicle_journey_id: number | null;
  stop_activity_id: number | null;
};
export type transmodel_tracks = {
  id: string;
  from_atco_code: string;
  to_atco_code: string;
  geometry: string | null;
  distance: number | null;
};
export type transmodel_vehiclejourney = {
  id: string;
  start_time: Timestamp | null;
  direction: string | null;
  journey_code: string | null;
  line_ref: string | null;
  departure_day_shift: boolean;
  service_pattern_id: number | null;
  block_number: string | null;
};
export type ui_lta = {
  id: Generated<number>;
  name: string;
};
export type DB = {
  Alert: Alert;
  all_operators: all_operators;
  ApiInfo: ApiInfo;
  avl_line_level_monitoring: avl_line_level_monitoring;
  bods_organisation: bods_organisation;
  bods_organisationoperator: bods_organisationoperator;
  bods_user: bods_user;
  bods_userorganisation: bods_userorganisation;
  corridor: corridor;
  corridor_stops: corridor_stops;
  distinct_routes: distinct_routes;
  expected_journeys: expected_journeys;
  expected_operators: expected_operators;
  expected_services: expected_services;
  FeatureFlag: FeatureFlag;
  feed_monitor_daily_summary: feed_monitor_daily_summary;
  feed_monitor_hourly_summary: feed_monitor_hourly_summary;
  feed_monitor_minute_summary: feed_monitor_minute_summary;
  feed_monitor_summary: feed_monitor_summary;
  login_details: login_details;
  naptan_adminarea: naptan_adminarea;
  naptan_adminarea_with_shape: naptan_adminarea_with_shape;
  naptan_locality: naptan_locality;
  naptan_stoppoint_latlong: naptan_stoppoint_latlong;
  noc_adminarea: noc_adminarea;
  organisation_organisation_admin_areas: organisation_organisation_admin_areas;
  performance_statistics: performance_statistics;
  service_details: service_details;
  servicepattern_route: servicepattern_route;
  SiriVMPositions: SiriVMPositions;
  Timetable: Timetable;
  timetable_frequent_summary_services: timetable_frequent_summary_services;
  timetable_summary_operator_t: timetable_summary_operator_t;
  timetable_summary_service_tz: timetable_summary_service_tz;
  timetable_summary_stops_tz: timetable_summary_stops_tz;
  timetable_threshold_summary: timetable_threshold_summary;
  Tokens: Tokens;
  transmodel_servicepatternstop: transmodel_servicepatternstop;
  transmodel_tracks: transmodel_tracks;
  transmodel_vehiclejourney: transmodel_vehiclejourney;
  ui_lta: ui_lta;
};
