/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alert {
  alert: string | null;
  alert_id: string | null;
  created_by: number | null;
  event_hysterisis: Numeric | null;
  event_threshold: Numeric | null;
  id: string;
  send_to: number | null;
}

export interface AllOperators {
  name: string | null;
  operatorid: number | null;
  operatorref: string | null;
}

export interface ApiInfo {
  build_number: string;
  feature_flag_id: string;
  id: string;
  timezone: string;
  version: string;
}

export interface AvlLineLevelMonitoring {
  last_recorded_at_time: Timestamp;
  line_name: string;
  operator_noc: string;
}

export interface BodsOrganisation {
  id: number | null;
  is_abods_global_viewer: boolean | null;
  name: string | null;
}

export interface BodsOrganisationoperator {
  operatorref: string | null;
  organisation_id: number | null;
}

export interface BodsUser {
  account_type: number | null;
  admin_org: number | null;
  email: string | null;
  first_name: string | null;
  id: number | null;
  is_active: boolean | null;
  is_superuser: boolean | null;
  last_name: string | null;
  password: string | null;
  username: string | null;
}

export interface BodsUserorganisation {
  organisation_id: number | null;
  user_id: number | null;
}

export interface Corridor {
  corridor_id: Generated<Int8>;
  corridor_name: string | null;
  organisation_id: Int8 | null;
  user_id: Int8 | null;
}

export interface CorridorStops {
  corridor_id: Int8 | null;
  corridor_index: Int8 | null;
  stop_id: Int8 | null;
}

export interface DistinctRoutes {
  id: Generated<number>;
  route: string;
}

export interface ExpectedJourneys {
  admin_area_id: number[] | null;
  date_of_journey: Timestamp | null;
  day_of_week: number | null;
  direction: string | null;
  expected_journey_end: Timestamp | null;
  expected_journey_start: Timestamp | null;
  group_id: string | null;
  journey_code: string | null;
  journey_pattern_description: string | null;
  line_name: string | null;
  noc_and_line_and_servicecode: string | null;
  operator_noc: string | null;
  stop_count: number | null;
  vehicle_journey_id: number | null;
}

export interface ExpectedOperators {
  date_of_journey: Timestamp | null;
  operator_name: string | null;
  operator_noc: string | null;
}

export interface FeatureFlag {
  consolidate_histogram: boolean;
  corridor_stats_timezone_enabled: boolean;
  freshdesk_enabled: boolean;
  id: string;
  journey_insights_enabled: boolean;
  line_direction_filtering: boolean;
  sso_enabled: boolean;
  stop_index_filtering: boolean;
  tagging_include_bank_holidays: boolean;
  vehicle_replay_from_timestream: boolean;
}

export interface FeedMonitorDailySummary {
  availability: Numeric | null;
  date_of_journey: Timestamp;
  id: Generated<Int8>;
  operator_noc: string;
  update_frequency: number | null;
}

export interface FeedMonitorHourlySummary {
  actual: number;
  expected: number;
  id: Generated<Int8>;
  operator_noc: string;
  received_interval: Timestamp;
}

export interface FeedMonitorMinuteSummary {
  actual: number;
  date_of_journey: Timestamp;
  expected: number;
  id: Generated<Int8>;
  live_locations: number;
  operator_noc: string;
  received_interval: Timestamp;
}

export interface FeedMonitorSummary {
  availability: Numeric | null;
  id: Generated<Int8>;
  last_outage: Timestamp | null;
  operator_noc: string;
  unavailable_since: Timestamp | null;
  update_frequency: number | null;
}

export interface LoginDetails {
  data_monitoring_access_count: number | null;
  data_monitoring_access_refresh: Timestamp | null;
  last_login: Timestamp;
  user_id: number;
}

export interface NaptanAdminarea {
  atco_code: string;
  id: Int8;
  name: string;
  traveline_region_id: string;
  ui_lta_id: number | null;
}

export interface NaptanAdminareaWithShape {
  atco_code: string | null;
  id: Int8 | null;
  name: string | null;
  st_asgeojson: string | null;
}

export interface NaptanLocality {
  admin_area_id: number | null;
  district_id: number | null;
  easting: number;
  gazetteer_id: string;
  name: string;
  northing: number;
}

export interface NaptanStoppointLatlong {
  admin_area_id: number | null;
  atco_code: string | null;
  bus_stop_type: string | null;
  common_name: string | null;
  id: Int8 | null;
  indicator: string | null;
  latitude: number | null;
  locality_id: string | null;
  longitude: number | null;
  naptan_code: string | null;
  stop_areas: string[] | null;
  stop_type: string | null;
  street: string | null;
}

export interface OrganisationOrganisationAdminAreas {
  adminarea_id: number | null;
  id: number | null;
  organisation_id: number | null;
}

export interface PerformanceStatistics {
  date_period_end: Timestamp | null;
  date_period_start: Timestamp | null;
  early_count: number | null;
  is_timing_point: boolean | null;
  late_count: number | null;
  line_name: string | null;
  noc_and_line_and_servicecode: string | null;
  on_time_count: number | null;
  on_time_percentage: Numeric | null;
  operator_noc: string | null;
  percentage_change: Numeric | null;
  period_type: string | null;
  service_name: string | null;
  total_count: number | null;
  trend_early_count: number | null;
  trend_late_count: number | null;
  trend_on_time_count: number | null;
  trend_percentage: Numeric | null;
  trend_period_end: Timestamp | null;
  trend_period_start: Timestamp | null;
  trend_total_count: number | null;
}

export interface ServiceDetails {
  line_name: string | null;
  noc_and_line_and_servicecode: string;
  operator_noc: string | null;
  service_name: string | null;
}

export interface ServicepatternRoute {
  distinct_route_id: number;
  noc_and_line_and_servicecode: string;
}

export interface SiriVMPositions {
  batch_id: Int8 | null;
  date_of_journey: Timestamp;
  departure_time: Timestamp | null;
  destination_ref: string | null;
  direction_ref: string | null;
  group_id: string | null;
  journey_ref: string;
  latitude: number | null;
  line_name: string;
  load_time_stamp: Generated<Timestamp | null>;
  longitude: number | null;
  operator_ref: string;
  origin_ref: string | null;
  recorded_at_time: Timestamp;
  response_time_stamp: Timestamp | null;
  siri_vm_positions_id: Generated<Int8>;
  vehicle_ref: string;
}

export interface Timetable {
  actual_departure_time: Timestamp | null;
  actual_headway: number | null;
  admin_area_id: number | null;
  atco_code: string | null;
  common_name: string | null;
  date_of_journey: Timestamp;
  day_of_week: number | null;
  departure_day_shift: boolean | null;
  direction: string | null;
  expected_departure_time: Timestamp | null;
  expected_headway: number | null;
  group_id: string | null;
  headway_time_difference: number | null;
  incomplete_reason: number | null;
  is_timing_point: boolean | null;
  journey_code: string | null;
  line_name: string | null;
  load_time_stamp: Generated<Timestamp | null>;
  locality_id: string | null;
  off_set: number | null;
  operator_name: string;
  operator_noc: string;
  otp_state: string | null;
  previous_group_id: string | null;
  registered: boolean | null;
  reprocessing_required: boolean | null;
  service_code: string;
  servicepattern_id: number | null;
  set_down: boolean | null;
  siri_vm_position_id: number | null;
  stop_id: Int8 | null;
  stop_index: number | null;
  stop_latitude: number | null;
  stop_longitude: number | null;
  stop_type: string | null;
  time_difference: number | null;
  timestamp_after_estimate: Timestamp | null;
  timetable_id: Generated<Int8>;
  vehiclejourney_id: number | null;
  xml_file_name: string | null;
}

export interface TimetableFrequentSummaryServices {
  actual_headway: Numeric;
  avg_time_difference: Numeric;
  date_of_journey: Timestamp;
  day_of_week: number;
  departure_hour: Timestamp;
  departure_hour_only: string;
  estimated: boolean;
  excess_wait_time: Numeric;
  expected_headway: Numeric;
  headway_stops_count: Numeric;
  is_timing_point: boolean | null;
  line_name: string;
  max_early: number;
  max_late: number;
  noc_and_line_and_servicecode: string;
  operator_noc: string;
  service_code: string;
  timetable_id: Generated<Int8>;
}

export interface TimetableSummaryOperatorT {
  admin_areas: number[];
  avg_time_difference: Numeric;
  completed: number | null;
  date_of_journey: Timestamp;
  day_of_week: number;
  departure_hour: Timestamp;
  departure_hour_only: string;
  early_count: number | null;
  estimated: Generated<boolean>;
  incomplete_reason: number | null;
  is_timing_point: boolean;
  late_count: number | null;
  max_early: number;
  max_late: number;
  on_time_count: number | null;
  operator_noc: string;
  scheduled: number | null;
  timetable_id: Generated<Int8>;
}

export interface TimetableSummaryServiceTz {
  admin_areas: number[] | null;
  avg_time_difference: Numeric | null;
  completed: number | null;
  date_of_journey: Timestamp;
  day_of_week: number;
  departure_hour: Timestamp;
  departure_hour_only: string;
  early_count: number | null;
  estimated: Generated<boolean>;
  incomplete_reason: number | null;
  is_timing_point: boolean;
  late_count: number | null;
  line_name: string;
  max_early: number;
  max_late: number;
  noc_and_line_and_servicecode: string;
  on_time_count: number | null;
  operator_noc: string;
  scheduled: number | null;
  timetable_id: Generated<Int8>;
}

export interface TimetableSummaryStopsTz {
  avg_time_difference: Numeric | null;
  common_name: string;
  completed: number | null;
  date_of_journey: Timestamp;
  day_of_week: number;
  departure_hour: Timestamp;
  departure_hour_only: string;
  early_count: number | null;
  estimated: Generated<boolean>;
  incomplete_reason: number | null;
  is_timing_point: boolean;
  late_count: number | null;
  line_name: string;
  locality_id: string;
  max_early: number;
  max_late: number;
  noc_and_line_and_servicecode: string;
  on_time_count: number | null;
  operator_noc: string;
  scheduled: number | null;
  service_code: string;
  stop_id: Int8;
  stop_latitude: number;
  stop_longitude: number;
  timetable_id: Generated<Int8>;
}

export interface TimetableThresholdSummary {
  admin_areas: number[] | null;
  date_of_journey: Timestamp | null;
  day_of_week: number | null;
  departure_hour: string | null;
  departure_hour_only: string | null;
  estimated: Generated<boolean | null>;
  is_timing_point: boolean | null;
  line_name: string | null;
  noc_and_line_and_servicecode: string | null;
  operator_noc: string | null;
  otp_count: Int8 | null;
  service_name: string | null;
  threshold_id: Generated<Int8>;
  time_diff_minutes: number | null;
}

export interface Tokens {
  expires: Generated<Timestamp | null>;
  token: string | null;
  user_id: number;
}

export interface TransmodelServicepatternstop {
  atco_code: string;
  departure_time: string | null;
  id: Int8;
  is_timing_point: boolean;
  naptan_stop_id: number | null;
  sequence_number: number;
  service_pattern_id: number;
  stop_activity_id: number | null;
  txc_common_name: string | null;
  vehicle_journey_id: number | null;
}

export interface TransmodelTracks {
  distance: number | null;
  from_atco_code: string;
  geometry: string | null;
  id: Int8;
  to_atco_code: string;
}

export interface TransmodelVehiclejourney {
  block_number: string | null;
  departure_day_shift: boolean;
  direction: string | null;
  id: Int8;
  journey_code: string | null;
  line_ref: string | null;
  service_pattern_id: number | null;
  start_time: string | null;
}

export interface UiLta {
  id: Generated<number>;
  name: string;
}

export interface DB {
  Alert: Alert;
  all_operators: AllOperators;
  ApiInfo: ApiInfo;
  avl_line_level_monitoring: AvlLineLevelMonitoring;
  bods_organisation: BodsOrganisation;
  bods_organisationoperator: BodsOrganisationoperator;
  bods_user: BodsUser;
  bods_userorganisation: BodsUserorganisation;
  corridor: Corridor;
  corridor_stops: CorridorStops;
  distinct_routes: DistinctRoutes;
  expected_journeys: ExpectedJourneys;
  expected_operators: ExpectedOperators;
  FeatureFlag: FeatureFlag;
  feed_monitor_daily_summary: FeedMonitorDailySummary;
  feed_monitor_hourly_summary: FeedMonitorHourlySummary;
  feed_monitor_minute_summary: FeedMonitorMinuteSummary;
  feed_monitor_summary: FeedMonitorSummary;
  login_details: LoginDetails;
  naptan_adminarea: NaptanAdminarea;
  naptan_adminarea_with_shape: NaptanAdminareaWithShape;
  naptan_locality: NaptanLocality;
  naptan_stoppoint_latlong: NaptanStoppointLatlong;
  organisation_organisation_admin_areas: OrganisationOrganisationAdminAreas;
  performance_statistics: PerformanceStatistics;
  service_details: ServiceDetails;
  servicepattern_route: ServicepatternRoute;
  SiriVMPositions: SiriVMPositions;
  Timetable: Timetable;
  timetable_frequent_summary_services: TimetableFrequentSummaryServices;
  timetable_summary_operator_t: TimetableSummaryOperatorT;
  timetable_summary_service_tz: TimetableSummaryServiceTz;
  timetable_summary_stops_tz: TimetableSummaryStopsTz;
  timetable_threshold_summary: TimetableThresholdSummary;
  Tokens: Tokens;
  transmodel_servicepatternstop: TransmodelServicepatternstop;
  transmodel_tracks: TransmodelTracks;
  transmodel_vehiclejourney: TransmodelVehiclejourney;
  ui_lta: UiLta;
}
