scalar DateTime
scalar Date

type Query {
    user(id: String): UserType
    users: [UserType!]
    apiInfo: ApiInfoType!
    roles: [RoleType!]
    userAlerts: [AlertType!]
    userAlert(alertId: String!): AlertType!
    operator(operatorId: String!): OperatorType
    operators(operatorId: String, filterBy: OperatorFilterInput): OperatorsPage!
    adminAreas(adminAreaIds: [String!]): [AdminAreasType]
    onTimePerformance: OnTimePerformanceType
    headwayMetrics: HeadwayMetricsType!
    serviceInfo(serviceId: String!): ServiceInfoType
    vehicleReplay: VehicleReplayNamespace!
    servicePatternsInfo(servicePatternIds: [String!]): [ServicePatternType]
    vehicleJourney(vehicleJourneyId: String!):  [VehicleJourneyType]!
    timingPatternDetail(timingPatternId: String!): [TimingPatternDetailType]
    corridor: CorridorNamespace!
    invitation(key: String!): InvitationType
    events(operatorId: String!, start: DateTime!, end: DateTime!):EventResponse
    eventStats(operatorId: String!, start: Date!, end: Date!):[EventStatsType]
}

type Mutation {
    login(username: String!, password: String!): LoginResponse!
    logout: Boolean!
    addUserAlert(payload: AlertInputType!): MutationResponseType!
    updateUserAlert(alertId: String!, payload: AlertInputType!): MutationResponseType!
    deleteUserAlert(alertId: String!): MutationResponseType!
    createCorridor(payload: CorridorInputType!): MutationResponseType!
    updateCorridor(inputs: CorridorUpdateInputType!): MutationResponseType!
    deleteCorridor(corridorId: Int!): MutationResponseType!
    requestResetPassword(email:String!): MutationResponseType!
    resetPassword(uid:String!, token: String!, password:String! confirmPassword:String!): MutationResponseType!
    verifyResetPasswordToken(uid:String!, token: String!): Boolean!
    signUp(payload: SignupPayloadType!): MutationResponseType!
    updateUser(username: String! payload: UserUpdateInput): UserUpdateResponseType!
    deleteUser(username: String!): MutationResponseType!
    inviteUser(payload: InvitationInput!): InvitationResponseType!
}

input OperatorFilterInput {
    operatorIds: [String!]
}

input SignupPayloadType {
    key: String!
    password: String!
    firstName: String!
    lastName: String!
}

type EventStatsType {
    count: Int!
    day: Date!
}

type EventResponse {
    items: [EventType!]
}

type EventType {
    timestamp: String!
    type: String!
    data: EventData!
}

type EventData {
    message: String!
}

type CorridorNamespace {
    getCorridor(corridorId: Int!): CorridorType
    corridorList: [CorridorType]
    stats(inputs: CorridorStatsInputType): CorridorStatsType
    addFirstStop(inputs: AddFirstStopInputType): [StopType]
    addSubsequentStops(stopList: [String!]!): [StopType]
}

input AddFirstStopInputType {
    searchString: String
    boundingBox: BoundingBoxInputType
}

input BoundingBoxInputType {
    maxLatitude: Float
    maxLongitude: Float
    minLatitude: Float
    minLongitude: Float
}

type CorridorType {
    createdBy: UserType
    id: Int!
    name: String!
    stops: [StopInfoType]
}

type CorridorStatsType {
    summaryStats: CorridorSummaryStatsType
    journeyTimeStats: [CorridorJourneyTimeStatsType]
    journeyTimeTimeOfDayStats: [CorridorStatsTimeOfDayType]
    journeyTimeDayOfWeekStats: [CorridorStatsDayOfWeekType]
    journeyTimeHistogram: [CorridorStatsHistogramType]
    journeyTimePerServiceStats: [CorridorStatsPerServiceType]!
    serviceLinks: [ServiceLinkType]
}

input CorridorStatsInputType {
    corridorId: String!
    fromTimestamp: DateTime!
    granularity: CorridorGranularity!
    stopList: [String]
    toTimestamp: DateTime!
}

type CorridorSummaryStatsType {
    averageJourneyTime: Int
    numberOfServices: Int
    scheduledTransits: Int
    totalTransits: Int
}

type CorridorJourneyTimeStatsType {
    avgTransitTime: Float
    maxTransitTime: Int!
    minTransitTime: Int!
    percentile25: Float
    percentile75: Float
    ts: String
}

type CorridorStatsTimeOfDayType {
    hour: Int!
    avgTransitTime: Float
    maxTransitTime: Int!
    minTransitTime: Int!
    percentile25: Float
    percentile75: Float
}

type CorridorStatsDayOfWeekType {
    avgTransitTime: Float
    maxTransitTime: Int!
    minTransitTime: Int!
    percentile25: Float
    percentile75: Float
    dow: Int!
}

type CorridorStatsPerServiceType {
    lineName: String!
    noc: String
    operatorName: String
    recordedTransits: Int
    scheduledTransits: Int
    servicePatternName: String!
    totalJourneyTime: Int
}

type ServiceLinkType {
    distance: Int!
    fromStop: String!
    linkRoute: String
    routeValidity: String!
    toStop: String!
}

type CorridorStatsHistogramType {
    hist: [CorridorHistogramType]
    ts: String
}

type CorridorHistogramType {
    bin: Int
    freq: Int
}

enum CorridorGranularity {
    day
    hour
    minute
}

type VehicleJourneyType {
    mode: String
    operatorId: String
    servicePatternId: String
    timingPatternId: String
    vehicleJourneyId: String
}

type TimingPatternDetailType {
    arrivalTimeOffset: Int!
    departureTimeOffset: Int!
    stopIndex: Int!
    timingPatternId: String!
    timingPoint: Boolean!
}

input VehicleReplayFilterInputType {
    filterOnStartTime: Boolean
    lineIds: [String]
}

input VehicleReplayInputType {
    filters: VehicleReplayFilterInputType
    fromTimestamp: DateTime!
    toTimestamp: DateTime!
}

type VehicleReplayNamespace {
    findJourneys(inputs: VehicleReplayInputType!): [UniqueJourneyType]
    getJourney(journeyId: String!, startTime: DateTime!): [GpsFeedType]!
}

type GpsFeedType {
    delay: Int!
    actualDelay: Int!
    feedStatus: GpsFeedStatus
    isTimingPoint: Boolean
    journeyStatus: GpsFeedJourneyStatus!
    lat: Float!
    lon: Float!
    operatorInfo: OperatorInfoType
    previousStopInfo: StopInfoType
    scheduledDeparture: String!
    serviceInfo: ServiceInfoType!
    servicePatternId: String
    startTime: String!
    ts: String!
    vehicleId: String!
    vehicleJourneyId: String
}

enum GpsFeedStatus {
    Active
    Stale
}

enum GpsFeedJourneyStatus {
    Completed
    Started
    Unknown
}

type UniqueJourneyType {
    serviceInfo: ServiceInfoType!
    startTime: String!
    vehicleJourneyId: String
}

type ServiceInfoType {
    serviceId: String!
    serviceName: String!
    serviceNumber: String!
}

type HeadwayMetricsType {
    frequentServices(operatorId: String!, fromTimestamp: DateTime!, toTimestamp: DateTime!): [FrequentServiceType]
    frequentServiceInfo(inputs: FrequentServiceInfoInputType): FrequentServiceInfoType
    headwayOverview(inputs: HeadwayInputType!): HeadwayOverviewType
    headwayTimeSeries(inputs: HeadwayInputType!): [HeadwayTimeSeriesType]
}

input CorridorUpdateInputType {
    id: Int!
    name: String!
    stopList: [String!]!
}

input HeadwayInputType {
    filters: HeadwayFiltersInputType
    fromTimestamp: DateTime
    toTimestamp: DateTime
}

input HeadwayFiltersInputType {
    dayOfWeekFlags: DayOfWeekFlagsInputType
    endTime: String
    granularity: Granularity
    lineIds: [String]
    operatorIds: [String]
    startTime: String
}

input DayOfWeekFlagsInputType {
    friday: Boolean!
    monday: Boolean!
    saturday: Boolean!
    sunday: Boolean!
    thursday: Boolean!
    tuesday: Boolean!
    wednesday: Boolean!
}

input FrequentServiceInfoInputType {
    filters: FrequentServiceInfoFilterType
    fromTimestamp: DateTime!
    toTimestamp: DateTime!
}

input FrequentServiceInfoFilterType {
    dayOfWeekFlags: DayOfWeekFlagsInputType
    endTime: String
    lineId: String
    operatorId: String
    startTime: String
}

type FrequentServiceType {
    serviceId: String!
}

type FrequentServiceInfoType {
    numHours: Int
    totalHours: Int
}

type HeadwayOverviewType {
    actualWaitTime: Float!
    excessWaitTime: Float!
    scheduledWaitTime: Float!
}

type HeadwayTimeSeriesType {
    ts: String!
    actualWaitTime: Float!
    excessWaitTime: Float!
    scheduledWaitTime: Float!
}

type TransitModelType {
    lines(filterBy: LineFilterType): PaginatedLineType!
}

input LineFilterType {
    lineIds: [String!]
}

type PaginatedLineType {
    items: [LineType]
}

type LineType {
    lineId: String!
    lineName: String!
    lineNumber: String!
    servicePatterns: [ServicePatternType]
}

type ServicePatternType {
    servicePatternId: String!
    name: String!
    stops: [StopType!]
    serviceLinks: [ServiceLinkType]!
}

type StopType {
    stopId: String!
    stopName: String!
    lon: Float!
    lat: Float!
    adminAreaId: String
    localityName: String
    sourceId: String
}

type AdminAreasType {
    adminAreaId: String!
    adminAreaName: String!
    shape: String!
}

type OperatorsPage {
    items: [OperatorType]!
}

type OperatorType {
    name: String
    nocCode: String!
    operatorId: String
    adminAreas: [AdminAreaInfoType]
    transitModel: TransitModelType
    feedMonitoring: FeedMonitoringType
}

type FeedMonitoringType {
    availability: Float
    feedStatus: Boolean
    historicalStats(date: Date!): HistoricalStatsType
    lastOutage: DateTime
    liveStats: LiveStatsType
    unavailableSince: DateTime
    vehicleStats(granularity: Granularity, start:DateTime!, end: DateTime!): [VehicleStatsType]!
}

type HistoricalStatsType {
    availability: Float
    updateFrequency: Int
}

type VehicleStatsType {
  actual: Int
  expected: Int
  timestamp: String!
}

type LiveStatsType {
    currentVehicles: Int
    expectedVehicles: Int
    feedAlerts: Int
    feedErrors: Int
    last20Minutes: [VehicleStatsType]!
    last24Hours: [VehicleStatsType]!
    updateFrequency: Int
}

type AdminAreaInfoType {
    adminAreaId: String!
}

input UserUpdateInput {
    firstName: String!
    lastName: String!
    role:RoleReferenceInput
}

type UserUpdateResponseType {
    error: String
    user: UserType
}

type MutationResponseType {
    error: String
    success: Boolean!
}

type InvitationResponseType {
    error: String
    invitation: InvitationType
}

type InvitationType {
    accepted: Boolean!
    email: String!
}

input InvitationInput {
    email: String!
    organisation: OrganisationReferenceInput
    role: RoleReferenceInput!
}

input OrganisationReferenceInput {
    id: String!
}

input RoleReferenceInput {
    id: String!
}

input AlertReferenceInput {
    id: String!
}

input AlertInputType {
    alertType: AlertTypeEnum
    sendTo: AlertReferenceInput!
    eventHysterisis: Int
    eventThreshold: Int
}

input CorridorInputType {
    name: String!
    stopIds: [String]!
}


type AlertType {
    alertId: String!
    alertType: AlertTypeEnum
    createdBy: UserType
    eventHysterisis: Int
    eventThreshold: Int
    sendTo: UserType
}

enum AlertTypeEnum {
    FeedComplianceFailure
    FeedFailure
    VehicleCountDisparity
}

type ApiInfoType {
    buildNumber: String!
    version: String!
}

type LoginResponse {
    success: Boolean!
    expiresAt: DateTime
}

type UserType {
    id: String!
    email: String!
    username: String!
    firstName: String
    lastName: String
    organisation: OrganisationType
    roles: [RoleType!]!
}

type OrganisationType{
    id: String!
    name: String!
}

type RoleType {
    id: String!
    name: String!
    scope: ScopeEnum!
}

enum ScopeEnum {
    organisation
    system
}

type OnTimePerformanceType {
    delayFrequency(inputs: PerformanceInputType!): [DelayFrequencyType!]
    operatorPerformance(inputs: PerformanceInputType!): OperatorPerformancePage
    punctualityDayOfWeek(inputs: PerformanceInputType!): [PunctualityDayOfWeekType!]
    punctualityOverview(inputs: PerformanceInputType!): PunctualityTotalsType
    punctualityTimeOfDay(inputs: PerformanceInputType!): [PunctualityTimeOfDayType!]
    punctualityTimeSeries(inputs: PerformanceInputType!): [PunctualityTimeSeriesType!]
    servicePerformance(inputs: PerformanceInputType!): [ServicePerformanceType!]
    servicePunctuality(inputs: ServicePerformanceInputType!): [ServicePunctualityType]
    stopPerformance(inputs: PerformanceInputType!): [StopPerformanceType!]
}

type DelayFrequencyType {
    bucket: Int!
    frequency: Int
}

type OperatorPerformancePage {
    pageInfo: PageInfo
    items: [OperatorPerformanceType]
}

type OperatorPerformanceType {
    actualDepartures: Int
    averageDelay: Float
    early: Int!
    late: Int!
    name: String
    nocCode: String
    onTime: Int!
    operatorId: String
    scheduledDepartures: Int
}

type PageInfo {
    next: Int
    totalCount: Int
}

type PunctualityDayOfWeekType {
    dayOfWeek: Int!
    early: Int!
    late: Int!
    onTime: Int!
}

type PunctualityTotalsType {
    averageDeviation: Float
    completed: Int!
    early: Int!
    late: Int!
    onTime: Int!
    scheduled: Int!
}

type PunctualityTimeOfDayType {
    early: Int!
    late: Int!
    onTime: Int!
    timeOfDay: String!
}

type PunctualityTimeSeriesType {
    early: Int!
    late: Int!
    onTime: Int!
    ts: String!
}

type ServicePerformanceType {
    actualDepartures: Int!
    averageDelay: Float!
    early: Int!
    late: Int!
    lineId: String
    onTime: Int!
    scheduledDepartures: Int!
    lineInfo: ServiceInfoType!
}

type OperatorInfoType {
    nocCode: String
    operatorId: String
    operatorName: String
}

type ServicePunctualityType {
    early: Int
    late: Int
    lineId: String
    lineInfo: ServiceInfoType
    nocCode: String
    onTime: Int
    rank: Float
    trend(fromTimestamp: DateTime!, toTimestamp: DateTime!): ServicePunctualityType
}

type StopPerformanceType {
    actualDepartures: Int!
    averageDelay: Float!
    early: Int!
    late: Int!
    lineId: String
    onTime: Int!
    scheduledDepartures: Int!
    stopId: String
    stopInfo: StopInfoType!
    timingPoint: Boolean
}


type StopInfoType {
    sourceId: String
    stopId: String!
    stopLocality: LocalityType!
    stopLocation: GpsPointType!
    stopName: String!
}

type LocalityType {
    localityAreaId: String
    localityAreaName: String
    localityId: String
    localityName: String
}

type GpsPointType {
    latitude: Float!
    longitude: Float!
}

input PerformanceInputType {
    filters: PerformanceFiltersInputType!
    fromTimestamp: DateTime!
    toTimestamp: DateTime!
}

input PerformanceFiltersInputType {
    adminAreaIds: [String!]
    dayOfWeekFlags: DayOfWeekFlagsInputType
    endTime: String
    excludeItoLineId: String
    granularity: Granularity
    lineIds: [String]
    maxDelay: Int
    minDelay: Int
    nocCodes: [String]
    onTimeMaxMinutes: Int
    onTimeMinMinutes: Int
    operatorIds: [String]
    startTime: String
    timingPointsOnly: Boolean
}

enum Granularity {
    day
    hour
    minute
    month
}

enum RankingOrder {
    ascending
    descending
}

input ServicePerformanceFiltersInputType {
    timingPointsOnly: Boolean
    operatorIds: [String]
}

input ServicePerformanceInputType {
    filters: ServicePerformanceFiltersInputType
    fromTimestamp: DateTime
    toTimestamp: DateTime
    order: RankingOrder
}
