[tools]
awscli = "latest"
usage = "latest"
jq = "latest"
serverless = "3.39.0"
node = "20.19.0"

[env]
REGION = "eu-west-2"

[settings]
asdf_compat = true
experimental = true
legacy_version_file = true

[tasks."setup:api"]
alias="setup"
description = "Setup task for the API"
dir = "abods-api"
run = "./setup.sh"

[tasks."db:sandbox"]
alias="db"
description = "Run a proxy to the sandbox DB using AWS SSM"
dir = "scripts"
run = "./db_connect.sh sandbox"

[tasks."db:dev"]
description = "Run a proxy to the dev DB using AWS SSM"
dir = "scripts"
run = "./db_connect.sh dev"

[tasks."db:test"]
description = "Run a proxy to the test DB using AWS SSM"
dir = "scripts"
run = "./db_connect.sh test"

[tasks."db:uat"]
description = "Run a proxy to the UAT DB using AWS SSM"
dir = "scripts"
run = "./db_connect.sh uat"

[tasks.app]
depends = ["build:frontend"]
description = "Run the front end in a dev server. Expects a local API to be running. In another terminal run the api task"
dir = "frontend"
run = "npm start"

[tasks."app:sandbox"]
depends = ["build:frontend"]
description = "Run the front end in a dev server. Connects to the deployed API in the sandbox environment"
dir = "frontend"
run = "npm start -- --proxy-config src/proxy.sandbox.conf.json"

[tasks."app:uat"]
description = "Run the front end in a dev server. Connects to the deployed API in the UAT environment. You must update your .env file"
dir = "frontend"
run = "npm start -- --proxy-config src/proxy.uat.conf.json"

[tasks.codegen]
description = "Perform code generation"
run = "npm run codegen"

[tasks."build:frontend"]
description = "Build front end"
depends = ["codegen"]
dir = "frontend"
run = "npm run build"

[tasks."build:backend"]
description = "Build API"
depends = ["codegen"]
dir = "abods-api"
run = "npm run build"

[tasks.build]
description = "Build all projects"
depends = ["build:frontend", "build:backend"]

[tasks.start]
description = "Run db proxy, api, and frontend"
run = "npm start"

[tasks.start-next]
description = "Run db proxy, api, and nextjs frontend (v2)"
run = "npm run start-next"
