fragment VehicleStat on VehicleStatsType {
  actual
  expected
  timestamp
}

fragment BasicOperator on OperatorFeedMonitoring {
  name
  operatorId
  feedMonitoring {
    feedStatus
    availability
    lastOutage
    unavailableSince
    liveStats {
      updateFrequency
    }
  }
}

fragment OperatorLiveStatus on OperatorFeedMonitoring {
  name
  operatorId
  feedMonitoring {
    feedStatus
    availability
    lastOutage
    unavailableSince
    liveStats {
      updateFrequency
      currentVehicles
      expectedVehicles
      last24Hours {
        ...VehicleStat
      }
      last20Minutes {
        ...VehicleStat
      }
    }
  }
}

fragment OperatorFeedHistory on OperatorFeedMonitoring {
  name
  operatorId
  feedMonitoring {
    historicalStats(date: $date) {
      updateFrequency
      availability
    }
    vehicleStats(granularity: minute, start: $start, end: $end) {
      ...VehicleStat
    }
  }
}

query feedMonitoringList {
  operatorsFeedMonitoring {
    ...BasicOperator
  }
}

query operatorSparklineStats($operatorIds: [String!]!) {
  operatorsFeedMonitoring(filterBy: { operatorIds: $operatorIds }) {
    operatorId
    feedMonitoring {
      liveStats {
        last24Hours {
          ...VehicleStat
        }
      }
    }
  }
}

query operatorLiveStatus($operatorId: String!) {
  operatorFeedMonitoring(operatorId: $operatorId) {
    ...OperatorLiveStatus
  }
}

query operatorHistoricStats(
  $operatorId: String!
  $date: Date!
  $start: DateTime!
  $end: DateTime!
) {
  operatorFeedMonitoring(operatorId: $operatorId) {
    ...OperatorFeedHistory
  }
}
