query headwayTimeSeries($params: HeadwayInputType!) {
  headwayMetrics {
    headwayTimeSeries(inputs: $params) {
      ts
      actual
      scheduled
      excess
    }
  }
}

query headwayOverview($params: HeadwayInputType!) {
  headwayMetrics {
    headwayOverview(inputs: $params) {
      excess
    }
  }
}

query headwayFrequentServices(
  $operatorId: String!
  $fromTimestamp: String!
  $toTimestamp: String!
) {
  headwayMetrics {
    frequentServices(
      operatorId: $operatorId
      fromTimestamp: $fromTimestamp
      toTimestamp: $toTimestamp
    ) {
      serviceId
    }
  }
}

query headwayFrequentServiceInfo($inputs: FrequentServiceInfoInputType!) {
  headwayMetrics {
    frequentServiceInfo(inputs: $inputs) {
      numHours
      totalHours
    }
  }
}
