query stopAnalysis(
  $adminAreaIds: [String!]!
  $boundingBox: BoundingBoxInputType!
  $fromTimestamp: DateTime!
  $lineIds: [String!]!
  $matchType: MatchType!
  $operatorIds: [String!]!
  $toTimestamp: DateTime!
) {
  stopAnalysis(
    inputs: {
      adminAreaIds: $adminAreaIds
      boundingBox: $boundingBox
      fromTimestamp: $fromTimestamp
      lineIds: $lineIds
      matchType: $matchType
      operatorIds: $operatorIds
      toTimestamp: $toTimestamp
    }
  ) {
    stopId
    atcoCode
    stopName
    localityName
    adminAreaName
    timingPoint
    latitude
    longitude
    early
    late
    onTime
    scheduledDepartures
    completedDepartures
    totalDelay
  }
}
