query journey($groupId: String!, $lineId: String!) {
  journey(groupId: $groupId, lineId: $lineId) {
    stops {
      estimatedDepartureUtc
      actualDepartureUtc
      scheduledDepartureUtc
      latitude
      longitude
      stopIndex
      stopName
      stopId
      isTimingPoint
      otp
      directionRef
      incompleteReason
      setDown
    }
    avls {
      recordedAtTimeUtc
      latitude
      longitude
      vehicleRef
      directionRef
    }
  }
}

query journeys($dateOfJourney: String!, $lineId: String!) {
  findJourneys(dateOfJourney: $dateOfJourney, lineId: $lineId) {
    groupId
    startTime
    serviceName
    serviceNumber
    operatorName
    operatorNoc
    directionRef
    vehicleJourneyId
  }
}

query servicePatternDistanceGeom($vehicleJourneyId: ID!) {
  getServicePatternDistanceGeom(vehicleJourneyId: $vehicleJourneyId) {
    distance
    geom
  }
}
