query avls($groupId: String!) {
  avls(groupId: $groupId) {
    recordedAtTimeUtc
    latitude
    longitude
    vehicleRef
    directionRef
  }
}

query route($groupId: String!) {
  route(groupId: $groupId) {
    estimatedDepartureUtc
    actualDepartureUtc
    scheduledDepartureUtc
    latitude
    longitude
    stopIndex
    stopName
    stopId
    isTimingPoint
    otp
    directionRef
  }
}

query journeys($dateOfJourney: Date!, $lineId: String!) {
  findJourneys(dateOfJourney: $dateOfJourney, lineId: $lineId) {
    groupId
    startTime
    serviceName
    serviceNumber
    operatorName
    operatorNoc
    directionRef
  }
}
