query journey($groupId: String!) {
  journey(groupId: $groupId) {
    stops {
      estimatedDepartureUtc
      actualDepartureUtc
      scheduledDepartureUtc
      latitude
      longitude
      stopIndex
      stopName
      stopId
      isTimingPoint
      otp
      directionRef
      incompleteReason
    }
    avls {
      recordedAtTimeUtc
      latitude
      longitude
      vehicleRef
      directionRef
    }
  }
}

query journeys($dateOfJourney: String!, $lineId: String!) {
  findJourneys(dateOfJourney: $dateOfJourney, lineId: $lineId) {
    groupId
    startTime
    serviceName
    serviceNumber
    operatorName
    operatorNoc
    directionRef
  }
}
