scalar DateTime
scalar Time
scalar Date

type Query {
  user: LoginInfo
  users: [UserType!]
  apiInfo: ApiInfoType
  userAlerts: [AlertType!]
  userAlert(alertId: String!): AlertType
  operatorFeedMonitoring(operatorId: String!): OperatorFeedMonitoring
  operatorsFeedMonitoring(
    filterBy: OperatorFilterInput
  ): [OperatorFeedMonitoring!]!
  operators(filterBy: OperatorFilterInput): [OperatorType!]!
  adminAreas: [AdminAreasType!]
  onTimePerformance: OnTimePerformanceType
  headwayMetrics: HeadwayMetricsType
  serviceInfo(serviceId: String!): ServiceInfoType
  corridor: CorridorNamespace
  invitation(key: String!): InvitationType
  events(operatorId: String!, start: DateTime!, end: DateTime!): EventResponse
  eventStats(
    operatorId: String!
    start: DateTime!
    end: DateTime!
  ): [EventStatsType!]!
  journey(groupId: String!, lineId: String!): JourneyResult!
  findJourneys(lineId: String!, dateOfJourney: String!): [Journey!]!
  lines(
    operatorIds: [String!]!
    inputDate: String!
    endDate: String
  ): [LineType!]!
  servicePatterns(operatorId: String!, lineId: String!): [ServicePatternType!]!
  stopAnalysis(inputs: StopAnalysisFiltersInput!): [StopStatistics!]!
  dashboardVehicles(operatorId: String): [DashboardVehicles!]!
  embeddedUrl: AWSQuicksightUser!
  userOrgs: [Organisation!]!
  distances(filterBy: DistancesFilterInput): [Distance!]!

  # Used by an external service, take care with changes
  # https://github.com/department-for-transport-BODS/bods/blob/dev/transit_odp/avl/require_attention/abods/registery.py#L52
  # eslint-disable-next-line @graphql-eslint/no-unused-fields
  avlLineLevelStatus(filters: AvlFiltersInput): [AvlLineLevelStatus!]!
}

type Distance {
  operatorId: String!
  operatorName: String!
  nocLineAndServiceCode: String!
  lineName: String!
  distance: Int
  avlDistance: Int
}

input DistancesFilterInput {
  orgId: String!
  operatorIds: [String!]
  nocLineAndServiceCodes: [String!]
  fromTimestamp: String!
  toTimestamp: String!
}

type Organisation {
  name: String!
  id: Int!
}

type AWSQuicksightUser {
  enabled: Boolean!
  url: String
}

type DashboardVehicles {
  operatorId: String!
  expected: Int!
  actual: Int!
}

input OperatorFilterInput {
  operatorIds: [String!]
  orgId: Int
}

type EventStatsType {
  count: Int!
  day: Date!
}

type EventResponse {
  items: [EventType!]!
}

type EventType {
  timestamp: String!
  type: String!
  data: EventData!
}

type EventData {
  message: String!
}

type CorridorNamespace {
  getCorridor(corridorId: Int!): CorridorType
  corridorList: [CorridorType!]!
  stats(inputs: CorridorStatsInputType!): CorridorStatsType
  addFirstStop(inputs: AddFirstStopInputType!): [StopType!]!
  addSubsequentStops(stopList: [String!]!): [StopType!]!
}

input AddFirstStopInputType {
  adminAreaIds: [String!]
  searchString: String
  boundingBox: BoundingBoxInputType
}

input BoundingBoxInputType {
  maxLatitude: Float!
  maxLongitude: Float!
  minLatitude: Float!
  minLongitude: Float!
}

type CorridorType {
  id: Int!
  name: String!
  stops: [StopInfoType!]!
}

type CorridorStatsType {
  summaryStats: CorridorSummaryStatsType
  transitTimeStats: [CorridorTransitTimeStatsType!]!
  transitTimeTimeOfDayStats: [CorridorStatsTimeOfDayType!]!
  transitTimeDayOfWeekStats: [CorridorStatsDayOfWeekType!]!
  transitTimeHistogram: [CorridorStatsHistogramType!]!
  transitTimePerServiceStats: [CorridorStatsPerServiceType!]!
  serviceLinks: [ServiceLinkType!]!
}

input CorridorStatsInputType {
  corridorId: String!
  fromTimestamp: String!
  granularity: CorridorGranularity!
  stopList: [String!]!
  toTimestamp: String!
  matchType: MatchType!
}

enum MatchType {
  estimated
  evidenced
}

enum StopTypeOption { # eslint-disable-line @graphql-eslint/no-unreachable-types
  timing_points
  all_stops
}

type CorridorSummaryStatsType {
  averageTransitTime: Int
  numberOfServices: Int
  scheduledTransits: Int
  totalTransits: Int
}

type CorridorTransitTimeStatsType {
  avgTransitTime: Float
  maxTransitTime: Int!
  minTransitTime: Int!
  percentile25: Float
  percentile75: Float
  ts: String
}

type CorridorStatsTimeOfDayType {
  hour: Int!
  avgTransitTime: Float
  maxTransitTime: Int!
  minTransitTime: Int!
  percentile25: Float
  percentile75: Float
}

type CorridorStatsDayOfWeekType {
  avgTransitTime: Float
  maxTransitTime: Int!
  minTransitTime: Int!
  percentile25: Float
  percentile75: Float
  dow: Int!
}

type CorridorStatsPerServiceType {
  lineName: String!
  noc: String
  operatorName: String
  recordedTransits: Int
  scheduledTransits: Int
  servicePatternName: String!
  totalTransitTime: Int
}

type CorridorStatsHistogramType {
  hist: [CorridorHistogramType!]!
  ts: String
}

type CorridorHistogramType {
  bin: Int
  freq: Int
}

enum CorridorGranularity {
  day
  hour
  minute
}

type Journey {
  directionRef: String
  startTime: String!
  groupId: String!
  serviceName: String!
  serviceNumber: String!
  operatorName: String!
  operatorNoc: String!
}

type ServiceInfoType {
  serviceId: String!
  serviceName: String!
  serviceNumber: String!
}

type Mutation {
  login(username: String!, password: String!): LoginResponse
  logout: Boolean!
  addUserAlert(payload: AlertInputType!): MutationResponseType!
  updateUserAlert(
    alertId: String!
    payload: AlertInputType!
  ): MutationResponseType!
  deleteUserAlert(alertId: String!): MutationResponseType!
  createCorridor(payload: CorridorInputType!): MutationResponseType!
  updateCorridor(inputs: CorridorUpdateInputType!): MutationResponseType!
  deleteCorridor(corridorId: Int!): MutationResponseType!
  requestResetPassword(email: String!): MutationResponseType!
  resetPassword(
    uid: String!
    token: String!
    password: String!
    confirmPassword: String!
  ): MutationResponseType!
  verifyResetPasswordToken(uid: String!, token: String!): Boolean!
  signUp(payload: SignupPayloadType!): MutationResponseType!
  updateUser(
    username: String!
    payload: UserUpdateInput!
  ): UserUpdateResponseType!
  deleteUser(username: String!): MutationResponseType!
  inviteUser(payload: InvitationInput!): InvitationResponseType!
}

input SignupPayloadType {
  key: String!
  password: String!
  firstName: String!
  lastName: String!
}

type HeadwayMetricsType {
  frequentServices(
    operatorId: String!
    fromTimestamp: String!
    toTimestamp: String!
  ): [FrequentServiceType!]
  frequentServiceInfo(
    inputs: FrequentServiceInfoInputType!
  ): FrequentServiceInfoType
  headwayOverview(inputs: HeadwayInputType!): HeadwayOverviewType
  headwayTimeSeries(inputs: HeadwayInputType!): [HeadwayTimeSeriesType!]
}

input CorridorInputType {
  name: String!
  stopIds: [String!]!
}

input CorridorUpdateInputType {
  id: Int!
  name: String!
  stopList: [String!]!
}

input HeadwayInputType {
  filters: HeadwayFiltersInputType!
  fromTimestamp: String!
  toTimestamp: String!
}

input HeadwayFiltersInputType {
  dayOfWeekFlags: DayOfWeekFlagsInputType
  endTime: String
  granularity: Granularity
  lineIds: [String!]
  nocCodes: [String!]
  operatorIds: [String!]
  startTime: String
  matchType: MatchType
}

input DayOfWeekFlagsInputType {
  friday: Boolean!
  monday: Boolean!
  saturday: Boolean!
  sunday: Boolean!
  thursday: Boolean!
  tuesday: Boolean!
  wednesday: Boolean!
}

input FrequentServiceInfoInputType {
  filters: FrequentServiceInfoFilterType!
  fromTimestamp: String!
  toTimestamp: String!
}

input FrequentServiceInfoFilterType {
  dayOfWeekFlags: DayOfWeekFlagsInputType
  endTime: String
  lineId: String
  noc: String
  operatorId: String
  startTime: String
}

type FrequentServiceType {
  serviceId: String!
}

type FrequentServiceInfoType {
  numHours: Int
  totalHours: Int
}

type HeadwayOverviewType {
  excess: Float
}

type HeadwayTimeSeriesType {
  ts: DateTime!
  actual: Float
  excess: Float
  scheduled: Float
}

type LineType {
  id: String!
  name: String!
  number: String!
  adminAreaIds: [Int!]!
}

type ServicePatternType {
  servicePatternId: String!
  stops: [StopType!]!
  serviceLinks: [ServiceLinkType!]!
}

type StopType {
  stopId: String!
  stopName: String!
  lon: Float!
  lat: Float!
  adminAreaId: String
  localityName: String
  sourceId: String
}

type ServiceLinkType {
  fromStop: String!
  toStop: String!
  distance: Float!
  routeValidity: RouteType!
  linkRoute: String
}

type AdminAreasType {
  id: String!
  name: String!
  shape: String!
}

type OperatorType {
  name: String!
  nocCode: String!
  operatorId: String!
  adminAreaIds: [String!]!
}

type OperatorFeedMonitoring {
  name: String!
  nocCode: String!
    @deprecated(reason: "nocCode is deprecated. Use operatorId instead.") # eslint-disable-line @graphql-eslint/require-deprecation-date
  operatorId: String!
  feedMonitoring: FeedMonitoringType
}

type FeedMonitoringType {
  operatorId: String! # eslint-disable-line @graphql-eslint/no-unused-fields
  availability: Float
  feedStatus: Boolean
  historicalStats(date: Date!): HistoricalStatsType
  lastOutage: DateTime
  liveStats: LiveStatsType
  unavailableSince: DateTime
  vehicleStats(
    granularity: Granularity!
    start: DateTime!
    end: DateTime!
  ): [VehicleStatsType!]
}

type HistoricalStatsType {
  availability: Float
  updateFrequency: Int
}

type VehicleStatsType {
  actual: Int!
  expected: Int!
  timestamp: DateTime!
}

type LiveStatsType {
  operatorId: String! # eslint-disable-line @graphql-eslint/no-unused-fields
  currentVehicles: Int
  expectedVehicles: Int
  feedAlerts: Int
  feedErrors: Int
  last20Minutes: [VehicleStatsType!]
  last24Hours: [VehicleStatsType!]
  updateFrequency: Int
}

input UserUpdateInput {
  firstName: String!
  lastName: String!
}

type UserUpdateResponseType {
  error: String
  user: UserType
}

type MutationResponseType {
  error: String
  success: Boolean!
}

type InvitationResponseType {
  error: String
  invitation: InvitationType
}

type InvitationType {
  accepted: Boolean!
  email: String!
}

input InvitationInput {
  email: String!
  organisation: OrganisationReferenceInput!
}

input OrganisationReferenceInput {
  id: String!
}

input AlertReferenceInput {
  id: String!
}

input AlertInputType {
  alertType: AlertTypeEnum!
  sendTo: AlertReferenceInput!
  eventHysterisis: Int
  eventThreshold: Int
}

type AlertType {
  alertId: String!
  alertType: AlertTypeEnum
  createdBy: UserType
  eventHysterisis: Int
  eventThreshold: Int
  sendTo: UserType
}

enum AlertTypeEnum {
  FeedComplianceFailure
  FeedFailure
  VehicleCountDisparity
  VehicleCountDisparityEvent
  FeedUnavailableEvent
  FeedAvailableEvent
}

type ApiInfoType {
  buildNumber: String!
  version: String!
}

type LoginResponse {
  success: Boolean!
  expiresAt: String
}

type LoginInfo {
  currentUserId: String!
  canViewServiceMonitoring: Boolean!
  canEditAllAlerts: Boolean!
  serviceMonitoringEmbedUrl: String
  flags: [FeatureFlag!]!
}

enum FeatureFlag {
  ServiceMonitoring
  DataMonitoring
  StopAnalysis
  DirectionsDisabled
  Distances
}

type UserType {
  id: String!
  username: String!
  firstName: String
  lastName: String
}

type OnTimePerformanceType {
  delayFrequency(inputs: PerformanceInputType!): [DelayFrequencyType!]
  operatorPerformance(inputs: PerformanceInputType!): OperatorPerformancePage
  punctualityDayOfWeek(
    inputs: PerformanceInputType!
  ): [PunctualityDayOfWeekType!]
  punctualityOverview(inputs: PerformanceInputType!): PunctualityTotalsType
  punctualityTimeOfDay(
    inputs: PerformanceInputType!
  ): [PunctualityTimeOfDayType!]
  punctualityTimeSeries(
    inputs: PerformanceInputType!
  ): [PunctualityTimeSeriesType!]
  servicePerformance(inputs: PerformanceInputType!): [ServicePerformanceType!]
  servicePunctuality(
    inputs: ServicePerformanceInputType!
  ): [ServicePunctualityType!]!
  stopPerformance(inputs: PerformanceInputType!): [StopPerformanceType!]
}

type DelayFrequencyType {
  bucket: Int!
  frequency: Int
}

type OperatorPerformancePage {
  pageInfo: PageInfo
  items: [OperatorPerformanceType!]!
}

type OperatorPerformanceType {
  early: Int!
  late: Int!
  name: String
  nocCode: String
  onTime: Int!
  operatorId: String
  averageDelay: Float
}

type PageInfo {
  next: Int
  totalCount: Int
}

type PunctualityDayOfWeekType {
  dayOfWeek: Int!
  early: Int!
  late: Int!
  onTime: Int!
}

type PunctualityTotalsType {
  averageDeviation: Float
  averageDelay: Float
  completed: Int!
  early: Int!
  late: Int!
  onTime: Int!
  scheduled: Int!
  incomplete: String! # Needs to be a JSON serialised mapping of number -> number
}

type PunctualityTimeOfDayType {
  early: Int!
  late: Int!
  onTime: Int!
  timeOfDay: Time!
}

type PunctualityTimeSeriesType {
  early: Int!
  late: Int!
  onTime: Int!
  ts: DateTime!
}

type ServicePerformanceType {
  actualDepartures: Int!
  averageDelay: Float
  countDelayed: Int
  early: Int!
  late: Int!
  lineId: String
  onTime: Int!
  scheduledDepartures: Int!
  lineInfo: ServiceInfoType!
  earlyInSeconds: Float
  lateInSeconds: Float
  onTimeInSeconds: Float
  direction: Direction
}

type ServicePunctualityType {
  early: Int
  late: Int
  lineId: String
  lineInfo: ServiceInfoType
  nocCode: String
  onTime: Int
  trend(
    fromTimestamp: DateTime!
    toTimestamp: DateTime!
  ): ServicePunctualityType
}

type StopPerformanceType {
  actualDepartures: Int!
  averageDelay: Float
  countDelayed: Int
  early: Int!
  late: Int!
  lineId: String
  onTime: Int!
  scheduledDepartures: Int!
  stopId: String!
  stopInfo: StopInfoType!
  timingPoint: Boolean!
  earlyInSeconds: Float
  lateInSeconds: Float
  onTimeInSeconds: Float
  direction: Direction
  averageScheduled: Float
  averageActual: Float
}

type StopInfoType {
  sourceId: String
  stopId: String!
  stopLocality: LocalityType!
  stopLocation: GpsPointType!
  stopName: String!
}

type LocalityType {
  localityAreaId: String
  localityAreaName: String
  localityId: String
  localityName: String
}

type GpsPointType {
  latitude: Float!
  longitude: Float!
}

input PerformanceInputType {
  filters: PerformanceFiltersInputType!
  fromTimestamp: String!
  paging: PagingInputType
  toTimestamp: String!
}

input PerformanceFiltersInputType {
  addNonTagged: Boolean
  adminAreaIds: [String!]
  dayOfWeekFlags: DayOfWeekFlagsInputType
  endTime: String
  excludedDates: [Date!]
  excludeItoLineId: String
  granularity: Granularity
  direction: [Direction]
  lineIds: [String!]
  maxDelay: Int
  minDelay: Int
  nocCodes: [String!]
  onTimeMaxMinutes: Int
  onTimeMinMinutes: Int
  operatorIds: [String!]
  startTime: String
  startTimes: [Time!]
  stopsSegment: StopsSegment
  tagIds: [Int!]
  timingPointsOnly: Boolean
  matchType: MatchType
}

enum Granularity {
  day
  hour
  minute
  month
}

enum Direction {
  all
  inbound
  outbound
  clockwise
  anticlockwise
}

enum StopsSegment {
  First
  Intermediate
}

input PagingInputType {
  after: Int!
  first: Int!
}

enum RankingOrder {
  ascending
  descending
}

input ServicePerformanceFiltersInputType {
  timingPointsOnly: Boolean
  operatorIds: [String!]
}

input ServicePerformanceInputType {
  filters: ServicePerformanceFiltersInputType!
  fromTimestamp: String!
  toTimestamp: String!
  order: RankingOrder!
}

type JourneyResult {
  stops: [Stop!]!
  avls: [AvlPoint!]!
}

type AvlPoint {
  recordedAtTimeUtc: String!
  latitude: Float!
  longitude: Float!
  vehicleRef: String!
  directionRef: String!
}

type Stop {
  actualDepartureUtc: String
  estimatedDepartureUtc: String
  scheduledDepartureUtc: String!
  latitude: Float!
  longitude: Float!
  stopIndex: Int!
  stopId: Int!
  stopName: String!
  isTimingPoint: Boolean!
  otp: OtpEnum
  directionRef: String!
  incompleteReason: Int!
  setDown: Boolean!
}

enum OtpEnum {
  Early
  Late
  OnTime
}

enum RouteType {
  VALID
  INVALID_NO_ROUTE_POINTS
}

# eslint-disable @graphql-eslint/no-unused-fields

input StopAnalysisFiltersInput {
  adminAreaIds: [String!]!
  boundingBox: BoundingBoxInputType!
  fromTimestamp: String!
  lineIds: [String!]!
  matchType: MatchType!
  operatorIds: [String!]!
  toTimestamp: String!
  dayOfWeekFlags: DayOfWeekFlagsInputType
  startTime: String
  endTime: String
}

type StopStatistics {
  atcoCode: String!
  stopName: String!
  localityName: String!
  adminAreaName: String!
  timingPoint: Boolean!
  latitude: Float!
  longitude: Float!
  early: Int!
  late: Int!
  onTime: Int!
  scheduledDepartures: Int!
  completedDepartures: Int!
  totalDelay: Float!
  earlyInSeconds: Float
  lateInSeconds: Float
  onTimeInSeconds: Float
  averageDelay: Int
  direction: String
  countDelayed: Int
  averageScheduled: Float
  averageScheduledTimingPoint: Float
  averageActual: Float
  averageActualTimingPoint: Float
}
"""
Filters for AvlLineLevelStatus

[BODS integration](https://github.com/department-for-transport-BODS/bods/blob/dev/transit_odp/avl/require_attention/abods/registery.py#L52) uses this so ensure all changes are backwards compatible
"""
input AvlFiltersInput {
  operatorNoc: String
  lineName: String
}

"""
Last Received AVL for on a Line basis

[BODS integrates](https://github.com/department-for-transport-BODS/bods/blob/dev/transit_odp/avl/require_attention/abods/registery.py#L52) with this endpoint so ensure all changes are backwards compatible
"""
type AvlLineLevelStatus {
  operatorNoc: String!
  lineName: String!
  lastRecordedAtTime: DateTime!
}

# eslint-enable @graphql-eslint/no-unused-fields
