useDotenv: true
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs20.x
  timeout: 899
  httpApi:
    cors:
      allowCredentials: true
      allowedOrigins:
        - http://localhost:4200 # abods front-end
      allowedMethods:
        - GET
        - POST
      allowedHeaders:
        - Content-Type
        - Authorization
functions:
  graphql:
    handler: src/index.default
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - src/**
    - tsconfig.json
