name: build application
run-name: build application from ${{ github.ref_name }} @ ${{ github.ref_name == 'dev' && 'dev' || 'sandbox' }}
permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - "sandbox"
      - "dev"
    paths:
      - "VERSION"
      - "abods-api/**"
      - "frontend/**"

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment ||
    github.event_name == 'release' && 'prod' ||
    startsWith(github.ref, 'refs/tags/v') && 'prod' ||
    github.ref_name == 'main' && 'uat' ||
    github.ref_name == 'test' && 'test' ||
    github.ref_name == 'dev' && 'dev' || 'sandbox' }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  RC_ENV: ${{ github.ref_name == 'dev' && 'dev' || 'sandbox' }}
  RC_DST: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET }}
  RC_DST_KMS_KEY_ID: ${{ vars.DEPLOYMENT_ARTEFACTS_KMS_KEY_ID }}

jobs:
  validation:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'dev' && 'dev' || 'sandbox' }}
    outputs:
      VERSION: ${{ steps.validate.outputs.VERSION }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-app-build-validation
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: validate job parameters
        env:
          BRANCH_CONDITION: ${{ !(contains(fromJSON('["test", "main"]'), github.ref_name) || startsWith(github.ref, 'refs/tags/v')) }}
        id: validate
        run: |
          if [[ ${BRANCH_CONDITION} == 'true' ]]; then
            if [[ ${GITHUB_REF_NAME} == 'dev' ]]; then
              new_version=$(yq e '.version' VERSION)
              echo "VERSION=${new_version}" >> "$GITHUB_OUTPUT"

              rc_path="$RC_DST/abods/releases/$new_version"
              if [[ `aws s3 ls s3://$rc_path|head` ]]; then
                echo "[INFO] Release candidate version [${new_version}] already exists. Version number must be incremented to allow for a new build. Exiting"
                exit 1
              else
                echo "[INFO] Running on development branch, building as release for promotion through to live"
              fi
            else
              echo "[INFO] Running on feature branch, building as release for sandbox environment"
              echo "VERSION=${GITHUB_REF_NAME//\//-}" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "[ERROR] It is only possible to build from dev or sandbox/a feature branch. Exiting"
            exit 1
          fi

  backend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'dev' && 'dev' || 'sandbox' }}
    needs: validation
    defaults:
      run:
        working-directory: abods-api

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-backend-build
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: package and push backend code
        env:
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods/releases/$VERSION/backend" || rc_path="abods/releases-dev/$VERSION/backend"

          sam build && \
            sam package \
              --s3-bucket $RC_DST \
              --s3-prefix $rc_path \
              --output-template-file packaged.yaml \
              --kms-key-id $RC_DST_KMS_KEY_ID

          aws s3 cp packaged.yaml s3://$RC_DST/$rc_path/
          aws s3 cp samconfig.yaml s3://$RC_DST/$rc_path/

          echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully built uploaded"

  frontend:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs: validation
    defaults:
      run:
        working-directory: frontend

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        environment: [sandbox, dev, test-build, uat-build, prod-build]
        isRelease:
          - ${{ contains(github.ref, 'dev') }}
        exclude:
          - isRelease: true
            environment: sandbox
          - isRelease: false
            environment: dev
          - isRelease: false
            environment: test-build
          - isRelease: false
            environment: uat-build
          - isRelease: false
            environment: prod-build

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-frontend-build
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: package and push frontend code
        env:
          CI: ""
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          ENVIRONMENT=$(cut -d '-' -f 1 <<< ${{ matrix.environment }})
          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods/releases/$VERSION/frontend/$ENVIRONMENT" || rc_path="abods/releases-dev/$VERSION/frontend/$ENVIRONMENT"

          # determine environment variables for build
          domain_name=`aws ssm get-parameter --name "/${{ vars.PROJECT_NAME }}/${ENVIRONMENT}/route53/hostedzone/name" \
            | jq -r '.Parameter.Value'`
          freshdesk_api_url="https://${domain_name}/freshdesk/"
          graphql_api_url="https://${domain_name}/api/graphql"
          mapbox_token="${{ secrets.MAPBOX_TOKEN }}"
          mapbox_style="mapbox://styles/${{ vars.MAPBOX_STYLE }}"
          mapbox_satellite_style="mapbox://styles/${{ vars.MAPBOX_SATELLITE_STYLE }}"

          jq --arg freshdesk_api_url "$freshdesk_api_url" \
             --arg graphql_api_url "$graphql_api_url" \
             --arg mapbox_token "$mapbox_token" \
             --arg mapbox_style "$mapbox_style" \
             --arg mapbox_satellite_style "$mapbox_satellite_style" \
             --arg ENVIRONMENT "$ENVIRONMENT" \
             '.apiUrl = $graphql_api_url | .analyticsId = "1234" | .mapboxToken = $mapbox_token | .mapboxStyle = $mapbox_style | .mapboxSatelliteStyle = $mapbox_satellite_style | .envName = $ENVIRONMENT | .freshdesk.apiUrl = $freshdesk_api_url' src/config.json > tmp.json && \
            mv tmp.json src/config.json

          npm install
          npx ng build -c production
          mv ./dist/raa-client/browser/* ./dist/raa-client

          echo "[INFO] Uploading application component (FRONTEND) for ${ENVIRONMENT^^}"
          aws s3 cp --recursive dist/raa-client s3://$RC_DST/$rc_path/
          aws s3 cp --recursive s3://$RC_DST/$rc_path/freshdesk s3://$RC_DST/$rc_path/freshdesk --metadata-directive REPLACE --content-type "text/html; charset=utf-8"

          echo "[INFO] Application component (FRONTEND) with version ${VERSION} successfully uploaded for ${ENVIRONMENT^^}"

  commit-and-tag:
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure') && contains(github.ref, 'dev') }}
    runs-on: ubuntu-latest
    needs:
      - validation
      - backend
      - frontend

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: commit and push changes
        env:
          VERSION: ${{ needs.validation.outputs.VERSION }}
        run: |
          echo "[INFO] Tagging commit as version [${VERSION}]"

          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global url.https://${{ github.token }}@github.com/.insteadOf https://github.com/

          git tag $VERSION
          git push --tags --force

  trigger-deploy-dev:
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure') && !(contains(fromJSON('["test", "main"]'), github.ref_name) || startsWith(github.ref, 'refs/tags/v')) }}
    runs-on: ubuntu-latest
    needs:
      - validation
      - backend
      - frontend
      - commit-and-tag

    permissions:
      contents: write

    steps:
      - name: trigger remote
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ github.repository }}
          event-type: automated-deploy-dev
          client-payload: '{ "environment": "${{ env.RC_ENV }}", "release_version": "${{ needs.validation.outputs.VERSION }}" }'
