name: pr-checks
on:
  pull_request:
    types: [synchronize]

permissions: read-all

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: |
          npm i
      - name: Check formatting
        run: |
          npm run fmt:check

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: abods-api

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: setup sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: build backend code
        run: |
          sam build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc

      - name: build frontend code
        run: |
          npm install
          npm run build:production
