name: pr-checks
on:
  pull_request:
    branches:
      - sandbox

permissions: read-all

jobs:
  formatting-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install
        run: npm i

      - name: Check for changes
        run: git diff --name-only --exit-code HEAD || (echo "It looks like generated files haven't been updated. You can do that by running 'npm install' in the root directory"; false)

      - name: Check types
        if: success() || failure()
        run: npm run type-check

      - name: Check formatting
        if: success() || failure()
        run: npm run fmt:check

      - name: Run linters
        if: success() || failure()
        run: npm run lint:check

      - name: Run tests
        if: success() || failure()
        run: npm run test:ci

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: abods-api

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: setup sam
        uses: aws-actions/setup-sam@v3
        with:
          use-installer: true

      - name: build backend code
        run: |
          sam build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc

      - name: build frontend code
        run: |
          npm install
          npm run build:production
