fragment OperatorDashboard on OperatorFeedMonitoring {
  name
  # Remove this when we're sure it's not used. There is no type safety where it is
  nocCode # eslint-disable-line @graphql-eslint/no-deprecated
  operatorId
  feedMonitoring {
    feedStatus
    liveStats {
      feedErrors
      feedAlerts
    }
  }
}

query dashboardOperatorList {
  operatorsFeedMonitoring {
    ...OperatorDashboard
  }
}

query dashboardOperatorVehicleCountsList($operatorId: String) {
  dashboardVehicles(operatorId: $operatorId) {
    operatorId
    expected
    actual
  }
}

query dashboardPerformanceStats($params: PerformanceInputType!) {
  onTimePerformance {
    punctualityOverview(inputs: $params) {
      onTime
      late
      early
    }
  }
}

query dashboardServiceRanking(
  $params: ServicePerformanceInputType!
  $trendFrom: DateTime!
  $trendTo: DateTime!
) {
  onTimePerformance {
    servicePunctuality(inputs: $params) {
      nocCode
      lineId
      lineInfo {
        serviceId
        serviceName
        serviceNumber
      }
      onTime
      early
      late
      trend(fromTimestamp: $trendFrom, toTimestamp: $trendTo) {
        onTime
        early
        late
      }
    }
  }
}
